# Generated by Django 4.1.4 on 2024-03-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problemnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='algorithm', max_length=2000)),
                ('remark', models.TextField(default='algorithm', max_length=2000)),
            ],
        ),
    ]
