# Generated by Django 4.1.4 on 2024-03-11 22:54

from django.db import migrations, models
import django.db.models.deletion
import questionnew.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20000)),
                ('type', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=questionnew.models.get_default_json)),
                ('stage', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemnew.problemnew')),
            ],
        ),
    ]
