name: Deploy to Fly

on:
  push:
    branches: [ main, staging ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup environment
        id: setup-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo "FLY_APP=your-staging-app-name" >> $GITHUB_ENV
            echo "FLY_API_TOKEN=${{ secrets.FLY_STAGING_TOKEN }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "FLY_APP=your-production-app-name" >> $GITHUB_ENV
            echo "FLY_API_TOKEN=${{ secrets.FLY_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Deploy
        run: flyctl deploy --app $FLY_APP
        working-directory: ./src/backend
